// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: location.proto

package org.alexvod.longitude;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface LocationOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional string name = 1;
    boolean hasName();
    String getName();
    
    // required double lat = 2;
    boolean hasLat();
    double getLat();
    
    // required double lng = 3;
    boolean hasLng();
    double getLng();
    
    // optional double altitude = 4;
    boolean hasAltitude();
    double getAltitude();
    
    // optional double accuracy = 5;
    boolean hasAccuracy();
    double getAccuracy();
    
    // optional int64 time = 6;
    boolean hasTime();
    long getTime();
  }
  public static final class Location extends
      com.google.protobuf.GeneratedMessageLite
      implements LocationOrBuilder {
    // Use Location.newBuilder() to construct.
    private Location(Builder builder) {
      super(builder);
    }
    private Location(boolean noInit) {}
    
    private static final Location defaultInstance;
    public static Location getDefaultInstance() {
      return defaultInstance;
    }
    
    public Location getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required double lat = 2;
    public static final int LAT_FIELD_NUMBER = 2;
    private double lat_;
    public boolean hasLat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public double getLat() {
      return lat_;
    }
    
    // required double lng = 3;
    public static final int LNG_FIELD_NUMBER = 3;
    private double lng_;
    public boolean hasLng() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public double getLng() {
      return lng_;
    }
    
    // optional double altitude = 4;
    public static final int ALTITUDE_FIELD_NUMBER = 4;
    private double altitude_;
    public boolean hasAltitude() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public double getAltitude() {
      return altitude_;
    }
    
    // optional double accuracy = 5;
    public static final int ACCURACY_FIELD_NUMBER = 5;
    private double accuracy_;
    public boolean hasAccuracy() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public double getAccuracy() {
      return accuracy_;
    }
    
    // optional int64 time = 6;
    public static final int TIME_FIELD_NUMBER = 6;
    private long time_;
    public boolean hasTime() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public long getTime() {
      return time_;
    }
    
    private void initFields() {
      name_ = "";
      lat_ = 0D;
      lng_ = 0D;
      altitude_ = 0D;
      accuracy_ = 0D;
      time_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasLat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLng()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, lat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, lng_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, altitude_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, accuracy_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(6, time_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, lat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, lng_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, altitude_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, accuracy_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, time_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.alexvod.longitude.Proto.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.alexvod.longitude.Proto.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.alexvod.longitude.Proto.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.alexvod.longitude.Proto.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.alexvod.longitude.Proto.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.alexvod.longitude.Proto.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.alexvod.longitude.Proto.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.alexvod.longitude.Proto.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.alexvod.longitude.Proto.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.alexvod.longitude.Proto.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.alexvod.longitude.Proto.Location prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.alexvod.longitude.Proto.Location, Builder>
        implements org.alexvod.longitude.Proto.LocationOrBuilder {
      // Construct using org.alexvod.longitude.Proto.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        lat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        lng_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        altitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        accuracy_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.alexvod.longitude.Proto.Location getDefaultInstanceForType() {
        return org.alexvod.longitude.Proto.Location.getDefaultInstance();
      }
      
      public org.alexvod.longitude.Proto.Location build() {
        org.alexvod.longitude.Proto.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.alexvod.longitude.Proto.Location buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.alexvod.longitude.Proto.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.alexvod.longitude.Proto.Location buildPartial() {
        org.alexvod.longitude.Proto.Location result = new org.alexvod.longitude.Proto.Location(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.lat_ = lat_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lng_ = lng_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.altitude_ = altitude_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.accuracy_ = accuracy_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.time_ = time_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.alexvod.longitude.Proto.Location other) {
        if (other == org.alexvod.longitude.Proto.Location.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasLat()) {
          setLat(other.getLat());
        }
        if (other.hasLng()) {
          setLng(other.getLng());
        }
        if (other.hasAltitude()) {
          setAltitude(other.getAltitude());
        }
        if (other.hasAccuracy()) {
          setAccuracy(other.getAccuracy());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasLat()) {
          
          return false;
        }
        if (!hasLng()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              lat_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              lng_ = input.readDouble();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              altitude_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              accuracy_ = input.readDouble();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              time_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string name = 1;
      private Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        
      }
      
      // required double lat = 2;
      private double lat_ ;
      public boolean hasLat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getLat() {
        return lat_;
      }
      public Builder setLat(double value) {
        bitField0_ |= 0x00000002;
        lat_ = value;
        
        return this;
      }
      public Builder clearLat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        lat_ = 0D;
        
        return this;
      }
      
      // required double lng = 3;
      private double lng_ ;
      public boolean hasLng() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public double getLng() {
        return lng_;
      }
      public Builder setLng(double value) {
        bitField0_ |= 0x00000004;
        lng_ = value;
        
        return this;
      }
      public Builder clearLng() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lng_ = 0D;
        
        return this;
      }
      
      // optional double altitude = 4;
      private double altitude_ ;
      public boolean hasAltitude() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public double getAltitude() {
        return altitude_;
      }
      public Builder setAltitude(double value) {
        bitField0_ |= 0x00000008;
        altitude_ = value;
        
        return this;
      }
      public Builder clearAltitude() {
        bitField0_ = (bitField0_ & ~0x00000008);
        altitude_ = 0D;
        
        return this;
      }
      
      // optional double accuracy = 5;
      private double accuracy_ ;
      public boolean hasAccuracy() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public double getAccuracy() {
        return accuracy_;
      }
      public Builder setAccuracy(double value) {
        bitField0_ |= 0x00000010;
        accuracy_ = value;
        
        return this;
      }
      public Builder clearAccuracy() {
        bitField0_ = (bitField0_ & ~0x00000010);
        accuracy_ = 0D;
        
        return this;
      }
      
      // optional int64 time = 6;
      private long time_ ;
      public boolean hasTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public long getTime() {
        return time_;
      }
      public Builder setTime(long value) {
        bitField0_ |= 0x00000020;
        time_ = value;
        
        return this;
      }
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        time_ = 0L;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:longitude.Location)
    }
    
    static {
      defaultInstance = new Location(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:longitude.Location)
  }
  
  public interface LocationInfoOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // repeated .longitude.Location location = 1;
    java.util.List<org.alexvod.longitude.Proto.Location> 
        getLocationList();
    org.alexvod.longitude.Proto.Location getLocation(int index);
    int getLocationCount();
  }
  public static final class LocationInfo extends
      com.google.protobuf.GeneratedMessageLite
      implements LocationInfoOrBuilder {
    // Use LocationInfo.newBuilder() to construct.
    private LocationInfo(Builder builder) {
      super(builder);
    }
    private LocationInfo(boolean noInit) {}
    
    private static final LocationInfo defaultInstance;
    public static LocationInfo getDefaultInstance() {
      return defaultInstance;
    }
    
    public LocationInfo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    // repeated .longitude.Location location = 1;
    public static final int LOCATION_FIELD_NUMBER = 1;
    private java.util.List<org.alexvod.longitude.Proto.Location> location_;
    public java.util.List<org.alexvod.longitude.Proto.Location> getLocationList() {
      return location_;
    }
    public java.util.List<? extends org.alexvod.longitude.Proto.LocationOrBuilder> 
        getLocationOrBuilderList() {
      return location_;
    }
    public int getLocationCount() {
      return location_.size();
    }
    public org.alexvod.longitude.Proto.Location getLocation(int index) {
      return location_.get(index);
    }
    public org.alexvod.longitude.Proto.LocationOrBuilder getLocationOrBuilder(
        int index) {
      return location_.get(index);
    }
    
    private void initFields() {
      location_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      for (int i = 0; i < getLocationCount(); i++) {
        if (!getLocation(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < location_.size(); i++) {
        output.writeMessage(1, location_.get(i));
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < location_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, location_.get(i));
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    @java.lang.Override
    protected Object writeReplace() throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.alexvod.longitude.Proto.LocationInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.alexvod.longitude.Proto.LocationInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.alexvod.longitude.Proto.LocationInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.alexvod.longitude.Proto.LocationInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.alexvod.longitude.Proto.LocationInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.alexvod.longitude.Proto.LocationInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.alexvod.longitude.Proto.LocationInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.alexvod.longitude.Proto.LocationInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.alexvod.longitude.Proto.LocationInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.alexvod.longitude.Proto.LocationInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.alexvod.longitude.Proto.LocationInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.alexvod.longitude.Proto.LocationInfo, Builder>
        implements org.alexvod.longitude.Proto.LocationInfoOrBuilder {
      // Construct using org.alexvod.longitude.Proto.LocationInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        location_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.alexvod.longitude.Proto.LocationInfo getDefaultInstanceForType() {
        return org.alexvod.longitude.Proto.LocationInfo.getDefaultInstance();
      }
      
      public org.alexvod.longitude.Proto.LocationInfo build() {
        org.alexvod.longitude.Proto.LocationInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.alexvod.longitude.Proto.LocationInfo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.alexvod.longitude.Proto.LocationInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.alexvod.longitude.Proto.LocationInfo buildPartial() {
        org.alexvod.longitude.Proto.LocationInfo result = new org.alexvod.longitude.Proto.LocationInfo(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          location_ = java.util.Collections.unmodifiableList(location_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.location_ = location_;
        return result;
      }
      
      public Builder mergeFrom(org.alexvod.longitude.Proto.LocationInfo other) {
        if (other == org.alexvod.longitude.Proto.LocationInfo.getDefaultInstance()) return this;
        if (!other.location_.isEmpty()) {
          if (location_.isEmpty()) {
            location_ = other.location_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLocationIsMutable();
            location_.addAll(other.location_);
          }
          
        }
        return this;
      }
      
      public final boolean isInitialized() {
        for (int i = 0; i < getLocationCount(); i++) {
          if (!getLocation(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 10: {
              org.alexvod.longitude.Proto.Location.Builder subBuilder = org.alexvod.longitude.Proto.Location.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addLocation(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .longitude.Location location = 1;
      private java.util.List<org.alexvod.longitude.Proto.Location> location_ =
        java.util.Collections.emptyList();
      private void ensureLocationIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          location_ = new java.util.ArrayList<org.alexvod.longitude.Proto.Location>(location_);
          bitField0_ |= 0x00000001;
         }
      }
      
      public java.util.List<org.alexvod.longitude.Proto.Location> getLocationList() {
        return java.util.Collections.unmodifiableList(location_);
      }
      public int getLocationCount() {
        return location_.size();
      }
      public org.alexvod.longitude.Proto.Location getLocation(int index) {
        return location_.get(index);
      }
      public Builder setLocation(
          int index, org.alexvod.longitude.Proto.Location value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationIsMutable();
        location_.set(index, value);
        
        return this;
      }
      public Builder setLocation(
          int index, org.alexvod.longitude.Proto.Location.Builder builderForValue) {
        ensureLocationIsMutable();
        location_.set(index, builderForValue.build());
        
        return this;
      }
      public Builder addLocation(org.alexvod.longitude.Proto.Location value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationIsMutable();
        location_.add(value);
        
        return this;
      }
      public Builder addLocation(
          int index, org.alexvod.longitude.Proto.Location value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureLocationIsMutable();
        location_.add(index, value);
        
        return this;
      }
      public Builder addLocation(
          org.alexvod.longitude.Proto.Location.Builder builderForValue) {
        ensureLocationIsMutable();
        location_.add(builderForValue.build());
        
        return this;
      }
      public Builder addLocation(
          int index, org.alexvod.longitude.Proto.Location.Builder builderForValue) {
        ensureLocationIsMutable();
        location_.add(index, builderForValue.build());
        
        return this;
      }
      public Builder addAllLocation(
          java.lang.Iterable<? extends org.alexvod.longitude.Proto.Location> values) {
        ensureLocationIsMutable();
        super.addAll(values, location_);
        
        return this;
      }
      public Builder clearLocation() {
        location_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      public Builder removeLocation(int index) {
        ensureLocationIsMutable();
        location_.remove(index);
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:longitude.LocationInfo)
    }
    
    static {
      defaultInstance = new LocationInfo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:longitude.LocationInfo)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
